name: base
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8.4
  - pandas=1.3.2
  - numpy=1.21.2
  - pytorch>=1.4
  - torchvision>=0.5
  - nltk
  - flask=2.0.1
  - gunicorn=20.1.0
  - scikit-learn=0.24.2
  - pip=21.2.4
  - pip:
    - torchviz
    - pysftp==0.2.9
    - pdfplumber==0.5.28
    - pytest==6.2.5
    - PyYAML==6.0
    - flask-login==0.5.0
    - flask-migrate==3.1.0
    - flask-sqlalchemy==2.5.1
    - flask-cors==3.0.10

